pipeline:
    build:
        image: git.lumeweb.com/lumeweb/ci-node
        commands:
            - yarn
            - yarn build
    package:
        image: ghcr.io/goreleaser/nfpm
        commands:
            - nfpm pkg --packager deb
