pipeline:
    build:
        image: git.lumeweb.com/lumeweb/ci-node
        commands:
            - yarn
            - yarn build
    package:
        image: ghcr.io/goreleaser/nfpm
        commands:
            - nfpm pkg --packager deb
    publish_focal:
        image: git.lumeweb.com/lumeweb/aptly-publisher
        settings:
            apt_username:
                from_secret: APT_USERNAME
            apt_password:
                from_secret: APT_PASSWORD
            repo: apt.web3relay.io
            folder: ubuntu
            distro: focal
            gpg_password:
                from_secret: GPG_PASSWORD
    publish_jammy:
        image: git.lumeweb.com/lumeweb/aptly-publisher
        settings:
            apt_username:
                from_secret: APT_USERNAME
            apt_password:
                from_secret: APT_PASSWORD
            repo: apt.web3relay.io
            folder: ubuntu
            distro: jammy
            gpg_password:
                from_secret: GPG_PASSWORD
    purge_cdn:
        image: git.lumeweb.com/lumeweb/do-cdn-purge
        settings:
            DIGITALOCEAN_ACCESS_TOKEN:
                from_secret: DIGITALOCEAN_ACCESS_TOKEN
            DIGITALOCEAN_CDN_ID:
                from_secret: DIGITALOCEAN_CDN_ID
