pipeline:
    build:
        image: cimg/node
        commands:
            - yarn
            - yarn build
    package:
        image: debian:stable-slim
        commands:
            - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
            - apt update
            - apt install -y nfpm
            - nfpm pkg --packager deb
