pipeline:
    build:
        image: cimg/node:current
        commands:
            - yarn
            - yarn build
    package:
        image: ghcr.io/goreleaser/nfpm
        commands:
            - apt install -y nfpm
            - nfpm pkg --packager deb
