pipeline:
    build:
        image: node:18.5.0-bullseye-slim
        commands:
            - apt-get update && apt-get -y install git python3 build-essential
            - yarn
            - yarn build
    package:
        image: debian:stable-slim
        commands:
            - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
            - apt update
            - apt install -y nfpm
            - nfpm pkg --packager deb
