pipeline:
    build:
        image: git.lumeweb.com/lumeweb/ci-node
        commands:
            - yarn
            - yarn build
    package:
        image: ghcr.io/goreleaser/nfpm
        commands:
            - nfpm pkg --packager deb
    publish_focal:
        image: git.lumeweb.com/lumeweb/aptly-publisher
        settings:
            apt_username:
                from_secret: apt_username
            apt_password:
                from_secret: apt_password
            repo: apt.web3relay.io
            folder: ubuntu
            distro: focal
            gpg_password:
                from_secret: gpg_password
    publish_jammy:
        image: git.lumeweb.com/lumeweb/aptly-publisher
        settings:
            apt_username:
                from_secret: apt_username
            apt_password:
                from_secret: apt_password
            repo: apt.web3relay.io
            folder: ubuntu
            distro: jammy
            gpg_password:
                from_secret: gpg_password
    purge_cdn:
        image: digitalocean/doctl:latest
        settings:
            do_access_token:
                from_secret: do_access_token
            do_cdn_id:
                from_secret: do_cdn_id
        commands:
            - export DIGITALOCEAN_ACCESS_TOKEN=$PLUGIN_DO_ACCESS_TOKEN
            - doctl compute cdn flush $PLUGIN_DO_CDN_ID
