version: 2.1

orbs:
    node: circleci/node@5.1.0


jobs:
    setup:
        docker:
            -   image: "cimg/node:lts"
        steps:
            -   add_ssh_keys:
                    fingerprints:
                        - "SHA256:Gs0mI8VeDvaMRBUlJMwnLgiBTodCWyHDXKSXQcXW1mo"
            - checkout
workflows:
    release:
        jobs:
            - setup
            -   node/run:
                    npm-run: build
                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/
            -   node/run:
                    npm-run: semantic-release
                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/

