version: 2.1

orbs:
    node: circleci/node@5.1.0


jobs:
    setup:
        docker:
            -   image: "cimg/node:lts"
        steps:
            -   add_ssh_keys:
                    fingerprints:
                        - "47:cf:a1:17:d9:81:8e:c5:51:e5:53:c8:33:e4:33:b9"
            - checkout
workflows:
    release:
        jobs:
            - setup
            -   node/run:
                    npm-run: build
                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/
            -   node/run:
                    npm-run: semantic-release
                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/

