version: 2.1

orbs:
    node: circleci/node@5.1.0
    ssh: credijusto/ssh@0.5.2
workflows:
    release:
        jobs:
            -   node/run:
                    name: build
                    npm-run: build
                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/
            -   node/run:
                    name: release
                    npm-run: semantic-release
                    requires:
                        - build
                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/

                    context:
                        - publish
                    setup:
                        -   add_ssh_keys:
                                fingerprints:
                                    - "47:cf:a1:17:d9:81:8e:c5:51:e5:53:c8:33:e4:33:b9"
                        -   ssh/ssh-add-host:
                                host_url: GITEA_HOST
