version: 2.1

orbs:
    node: circleci/node@5.1.0

workflows:
    release:
        jobs:
            release:
                contexts:
                    - publish
                docker:
                    -   image: "circleci/node:lts"
                steps:
                    - checkout
                    -   run:
                            name: Set Repo Origin
                            command: |
                                git remote set-url origin https://git.lumeweb.com/LumeWeb/relay.git
                    -   add_ssh_keys:
                            fingerprints:
                                - "SHA256:Gs0mI8VeDvaMRBUlJMwnLgiBTodCWyHDXKSXQcXW1mo"
                    -   node/run:
                            npm-run: build
                    -   node/run:
                            npm-run: semantic-release
                            environment:
                                CLOUDSMITH_API_KEY: $CLOUDSMITH_API_KEY
                filters:
                    branches:
                        only:
                            - master
                            - develop
                            - /^develop-.*$/
