name: Release
on:
    push:
        branches:
            - master
            - develop
            - "develop-*"
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set Repo Origin
              run: git remote set-url origin https://git.lumeweb.com/LumeWeb/relay.git
            - uses: webfactory/ssh-agent@v0.7.0
              with:
               ssh-private-key: ${{ secrets.GITEA_SSH_KEY }}
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Release
              run: npx semantic-release
              env:
                  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
